package edu.ucsc.refactor.cli;

import com.google.common.base.Preconditions;

/**
 * @author hsanchez@cs.ucsc.edu (Huascar A. Sanchez)
 */
public class ResultProcessor {
    private static final ResultProcessorVisitor VISITOR = new SysResultVisitor();

    private ResultProcessor(){}

    /**
     * Process a result generated by some Vesper command.
     *
     * @param result The result to be processed.
     */
    public static void process(Result result){
        process(result, VISITOR);
    }

    /**
     * Process a result generated by some Vesper command.
     *
     * @param result The result to be processed.
     * @param visitor The strategy for processing the result.
     */
    public static void process(Result result, ResultProcessorVisitor visitor){
        Preconditions.checkNotNull(result, "process() has been given a null result");
        Preconditions.checkNotNull(visitor, "process() has been given a null processor-visitor");
        result.accepts(visitor);
    }

}
